version: '3.7'
services:
  mongodb:
    container_name: contato-api-db
    image: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27017:27017
    networks: 
        - production-network

  app:
    container_name: contato-api-app
    restart: always
    build: .
    volumes:
      - .:/app/contato-api
      - ~/.m2:/root/.m2
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/contato_db
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    networks: 
        - production-network
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local
    name: mongo-data
 
networks: 
    production-network:
        driver: bridge